app:compileDebugJavaWithJavac error
:app:compileDebugJavaWithJavac
/Users/Spicycurryman/Desktop/Main/Projects/Wosyl-Delivery-1.0-master/and
roid/app/src/main/java/com/wosyldelivery/MainActivity.java:6: error:
package com.react.rnspinkit does not exist
import com.react.rnspinkit.RNSpinkitPackage;
                          ^
/Users/Spicycurryman/Desktop/Main/Projects/Wosyl-Delivery-1.0-master/and
roid/app/src/main/java/com/wosyldelivery/MainApplication.java:7: error:
package com.microsoft.codepush.react does not exist
import com.microsoft.codepush.react.CodePush;
                                   ^
/Users/Spicycurryman/Desktop/Main/Projects/Wosyl-Delivery-1.0-master/and
roid/app/src/main/java/com/wosyldelivery/MainApplication.java:8: error:
package com.oblador.vectoricons does not exist
import com.oblador.vectoricons.VectorIconsPackage;
                              ^
/Users/Spicycurryman/Desktop/Main/Projects/Wosyl-Delivery-1.0-master/and
roid/app/src/main/java/com/wosyldelivery/MainApplication.java:20:
error: <anonymous com.wosyldelivery.MainApplication$1> is not abstract
and does not override abstract method getPackages() in ReactNativeHost
  private final ReactNativeHost mReactNativeHost = new
ReactNativeHost(this) {

     ^
4 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.